### ISSUE TITLE
Question: Should the various naming rules have an option to ignore destructured arguments?

### ISSUE THREAD

**Issue by calinoracation** [DianaSuvorova/eslint-plugin-react-redux#12]
We use a ton of destructuring arguments in both `mapStateToProps` and sometimes will construct an object in `mapDispatchToProps` such as `{ actionCreator1, actionCreator2 }`. It seems that perhaps an option on those rules to not throw in such cases might be useful, but perhaps also have a strict version for folks who really want that strict behavior.

I'm not convinced the current behavior is a bug, but was curious what your thoughts on it were as I imagine it might be a pretty common use case.

**Comment by DianaSuvorova** [comment]
I agree, destructuring arguments seems like a very valid use case and I think it should be supported by default (with no additional configurations to the rule ). Let me look into supporting that.
