### ISSUE TITLE
v1.4.0 should be reverted, and rereleased as v2

### ISSUE THREAD

**Issue by ljharb** [DianaSuvorova/eslint-plugin-react-redux#16]
Renaming a rule is a breaking change.

**Comment by DianaSuvorova** [comment]
@ljharb , sorry I misunderstood your comment on the original PR. The referenced PR should trigger a major release. 
I don't think I can unpublish npm  module though. The best I could do is deprecating it.

**Comment by ljharb** [comment]
Right; you'd have to revert it, and publish a v1.4.1, and then restore it and publish a v2.
